// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.4.0-dev-wicked-fork
// source: copyfrom.go

package activities

import (
	"context"
	"time"
)

// iteratorForBulkInsert implements pgx.CopyFromSource.
type iteratorForBulkInsert struct {
	rows                 []BulkInsertParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsert) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsert) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Action,
		r.rows[0].Parameter,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForBulkInsert) Err() error {
	return nil
}

// -- timeout: 1s
func (q *Queries) BulkInsert(ctx context.Context, arg []BulkInsertParams) (int64, error) {
	ctx, cancel := context.WithTimeout(ctx, time.Millisecond*1000)
	defer cancel()
	q.db.CountIntent("activities.BulkInsert")
	return q.db.WCopyFrom(ctx, "activities.BulkInsert", []string{"activities"}, []string{"action", "parameter", "created_at"}, &iteratorForBulkInsert{rows: arg})
}

// eliminate unused error
var _ = time.Now()
