// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v2.4.0-dev-wicked-fork

package users

import (
	"encoding/json"
	"time"
)

type User struct {
	ID        int32           `json:"id"`
	Name      string          `json:"name"`
	Metadata  json.RawMessage `json:"metadata"`
	Image     string          `json:"image"`
	CreatedAt time.Time       `json:"created_at"`
}
